name: Build & Deploy to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-cf-pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build & Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    env:
      PGLITE_DB_PATH: ${{ github.workspace }}/pglite-db
      LEADERBOARD_PATH: ${{ github.workspace }}/leaderboard
      LEADERBOARD_DATA_PATH: ${{ github.workspace }}/leaderboard-data
      SCRAPER_PATHS: ${{ github.workspace }}/leaderboard-github-scraper ${{ github.workspace }}/leaderboard-slack-scraper

    steps:
      - name: üì• Checkout Leaderboard
        uses: actions/checkout@v5
        with:
          repository: ohcnetwork/leaderboard
          path: ${{ env.LEADERBOARD_PATH }}
          fetch-depth: 1

      - name: üì• Checkout GitHub Scraper
        uses: actions/checkout@v5
        with:
          repository: ohcnetwork/leaderboard-github-scraper
          path: ${{ github.workspace }}/leaderboard-github-scraper
          fetch-depth: 1

      - name: üì• Checkout Slack Scraper
        uses: actions/checkout@v5
        with:
          repository: ohcnetwork/leaderboard-slack-scraper
          path: ${{ github.workspace }}/leaderboard-slack-scraper
          fetch-depth: 1

      - name: üì• Checkout Leaderboard Data
        uses: actions/checkout@v5
        with:
          path: ${{ env.LEADERBOARD_DATA_PATH }}
          fetch-depth: 1

      - name: üì¶ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: üì¶ Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: |
            ${{ env.LEADERBOARD_PATH }}/pnpm-lock.yaml
            ${{ github.workspace }}/leaderboard-github-scraper/pnpm-lock.yaml
            ${{ github.workspace }}/leaderboard-slack-scraper/pnpm-lock.yaml

      - name: üì¶ Install Dependencies on all repositories
        run: |
          for repo in ${{ env.LEADERBOARD_PATH }} ${{ env.SCRAPER_PATHS }}; do
            cd $repo
            pnpm install
          done

      - name: üö¶ Prepare DB
        run: |
          for repo in ${{ env.LEADERBOARD_PATH }} ${{ env.SCRAPER_PATHS }}; do
            cd $repo
            pnpm db:prepare
          done;

          for repo in ${{ env.LEADERBOARD_PATH }} ${{ env.SCRAPER_PATHS }}; do
            cd $repo
            pnpm db:import
          done

      - name: üõ†Ô∏è Build Leaderboard
        working-directory: ${{ env.LEADERBOARD_PATH }}
        run: pnpm build

      - name: üåê Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.LEADERBOARD_PATH }}/out --project-name=${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
